// ============================================================
// Demo content — the narrative source for the demo workspace.
//
// Everything here is hand-written, static sample content. seed.ts turns
// these templates into dated entities relative to "today". NOTHING here
// ever calls an API or a model — the "AI" results (reply drafts, extracted
// tasks, classifications) are all pre-written below.
// ============================================================

import type { DemoEmailCategory, DemoTaskStatus } from './types'

// ---------- Identities & projects ----------

export const DEMO_IDENTITIES = [
  { id: 'idn-acme', name: 'Acme Corp', description: 'Your operations role at Acme Corp.' },
  { id: 'idn-atlas', name: 'Atlas Studio', description: 'Freelance consulting engagement.' },
  { id: 'idn-personal', name: 'Personal', description: 'Life admin and personal follow-ups.' },
]

export const DEMO_PROJECTS = [
  { id: 'prj-q2launch', identityId: 'idn-acme', name: 'Q2 Product Launch', description: 'Cross-functional launch of the v2 platform.' },
  { id: 'prj-vendor', identityId: 'idn-acme', name: 'Vendor & Renewals', description: 'Contracts, SaaS renewals and procurement.' },
  { id: 'prj-hiring', identityId: 'idn-acme', name: 'Eng Hiring', description: 'Backfilling two senior engineering roles.' },
  { id: 'prj-atlas', identityId: 'idn-atlas', name: 'Atlas Rebrand', description: 'Brand refresh and website rebuild.' },
  { id: 'prj-personal', identityId: 'idn-personal', name: 'Personal', description: 'Bills, appointments and personal admin.' },
]

export const DEMO_MATTERS = [
  { id: 'mat-signoff', projectId: 'prj-q2launch', title: 'Q2 launch sign-off', summary: 'Final approvals before the v2 launch ships.' },
  { id: 'mat-beta', projectId: 'prj-q2launch', title: 'Beta feedback triage', summary: 'Issues and ideas raised by beta users.' },
  { id: 'mat-northwind', projectId: 'prj-vendor', title: 'Northwind contract renewal', summary: 'Renewal negotiation with Northwind.' },
  { id: 'mat-backend', projectId: 'prj-hiring', title: 'Senior backend hire', summary: 'Interview loop for the senior backend role.' },
  { id: 'mat-homepage', projectId: 'prj-atlas', title: 'Atlas homepage redesign', summary: 'Round-based redesign of the Atlas homepage.' },
  { id: 'mat-lease', projectId: 'prj-personal', title: 'Apartment lease renewal', summary: 'Renewing the apartment lease for another year.' },
]

// ---------- Emails ----------

export interface EmailTemplate {
  id: string
  threadId: string
  subject: string
  senderName: string
  sender: string
  daysAgo: number
  hour: number
  classification: DemoEmailCategory | null
  classConfidence: number | null
  classReasoning: string | null
  awaitingReview: boolean
  hasAttachments: boolean
  projectId: string | null
  matterId: string | null
  bodyPreview: string
  bodyFull: string
  /** Pre-written reply draft revealed by the simulated "AI reply" action. */
  replyDraft: string | null
  /** Pre-written task revealed by the simulated "Extract task" action. */
  extractTask: ExtractTaskSpec | null
}

export interface ExtractTaskSpec {
  title: string
  summary: string
  actionItems: string[]
  urgency: number
  impact: number
  priorityReason: string
  deadlineOffset: number
  matterId: string | null
  projectId: string | null
}

export const DEMO_EMAILS: EmailTemplate[] = [
  {
    id: 'em-1',
    threadId: 'th-signoff',
    subject: 'Re: Q2 launch sign-off — final assets',
    senderName: 'Morgan Lee',
    sender: 'morgan@northwind.co',
    daysAgo: 0,
    hour: 8,
    classification: 'action',
    classConfidence: 0.96,
    classReasoning: 'Direct request for your approval with a same-day deadline.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-q2launch',
    matterId: 'mat-signoff',
    bodyPreview: 'Need your approval on the final asset delivery by end of day so we stay on schedule.',
    bodyFull:
      'Hi,\n\nDesign cleared everything on the 16th and the final assets are attached. I need your written approval on the asset delivery by end of day today so the launch stays on schedule.\n\nIf you are underwater we can push to next week, but I would rather not. Let me know.\n\nThanks,\nMorgan',
    replyDraft:
      'Hi Morgan,\n\nApproved — the final assets look good to me, no changes needed. Thanks for turning these around quickly.\n\nGo ahead and lock the schedule; I will flag the team that sign-off is done.\n\nBest,\nYou',
    extractTask: {
      title: 'Reply with approval on final launch assets',
      summary: 'Morgan needs written approval on the final asset delivery so the Q2 launch stays on schedule.',
      actionItems: ['Review the attached final assets', 'Send written approval to Morgan'],
      urgency: 5,
      impact: 5,
      priorityReason: 'Same-day deadline and it blocks the entire launch schedule.',
      deadlineOffset: 0,
      matterId: 'mat-signoff',
      projectId: 'prj-q2launch',
    },
  },
  {
    id: 'em-2',
    threadId: 'th-copy',
    subject: 'Launch page copy — needs your review',
    senderName: 'Sofia Diaz',
    sender: 'sofia@acme.io',
    daysAgo: 1,
    hour: 15,
    classification: 'action',
    classConfidence: 0.91,
    classReasoning: 'Asks you to review and edit a document before a deadline.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-q2launch',
    matterId: null,
    bodyPreview: 'First draft of the launch page copy is ready — can you review and edit by tomorrow?',
    bodyFull:
      'Hey,\n\nThe first draft of the launch page copy is in the shared doc. Could you review the hero and pricing sections and edit anything that feels off? I would like to hand it to design by tomorrow afternoon.\n\nThanks!\nSofia',
    replyDraft:
      'Hi Sofia,\n\nWill do — I will get you edits on the hero and pricing sections by tomorrow morning so design has the full day.\n\nThanks,\nYou',
    extractTask: null,
  },
  {
    id: 'em-3',
    threadId: 'th-beta',
    subject: 'Beta feedback: onboarding felt confusing',
    senderName: 'Priya Raman',
    sender: 'priya.r@betauser.com',
    daysAgo: 2,
    hour: 11,
    classification: 'uncertain',
    classConfidence: 0.54,
    classReasoning: 'Mixes praise with a concrete problem — unclear if a task is required.',
    awaitingReview: true,
    hasAttachments: false,
    projectId: 'prj-q2launch',
    matterId: 'mat-beta',
    bodyPreview: 'Loving the beta so far, but the onboarding steps were hard to follow on first run.',
    bodyFull:
      'Hi team,\n\nReally enjoying the beta — the task ranking is genuinely useful. One bit of feedback: the onboarding steps were hard to follow on my first run. I skipped two screens without realising and could not get back to them.\n\nHappy to jump on a call if useful.\n\nPriya',
    replyDraft: null,
    extractTask: {
      title: 'Fix onboarding back-navigation from beta feedback',
      summary: 'A beta user skipped onboarding screens with no way to return. Review the onboarding flow and add back-navigation.',
      actionItems: [
        'Reproduce the skipped-screen issue in onboarding',
        'Add back-navigation between onboarding steps',
        'Reply to Priya once shipped',
      ],
      urgency: 3,
      impact: 4,
      priorityReason: 'Affects every new user during their first impression of the product.',
      deadlineOffset: 4,
      matterId: 'mat-beta',
      projectId: 'prj-q2launch',
    },
  },
  {
    id: 'em-4',
    threadId: 'th-deploy',
    subject: 'Staging deploy complete for v2',
    senderName: 'Acme DevOps',
    sender: 'devops@acme.io',
    daysAgo: 1,
    hour: 9,
    classification: 'awareness',
    classConfidence: 0.88,
    classReasoning: 'Status update — informational, no request directed at you.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-q2launch',
    matterId: null,
    bodyPreview: 'v2 is now live on staging. No action needed — sharing for visibility.',
    bodyFull:
      'The v2 build was deployed to staging at 9:04am and all smoke tests passed. Sharing for visibility ahead of the launch sign-off — no action needed.\n\n— DevOps',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-5',
    threadId: 'th-signoff',
    subject: 'Q2 Launch — go / no-go meeting Thursday',
    senderName: 'Daniel Cho',
    sender: 'daniel@acme.io',
    daysAgo: 3,
    hour: 13,
    classification: 'action',
    classConfidence: 0.9,
    classReasoning: 'Requests your confirmation of attendance for a scheduled meeting.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-q2launch',
    matterId: 'mat-signoff',
    bodyPreview: 'Please confirm you can make the go/no-go meeting Thursday at 10am.',
    bodyFull:
      'Hi all,\n\nScheduling the Q2 launch go/no-go for Thursday at 10am. Your sign-off is on the agenda, so please confirm you can attend — if not we will need to move it.\n\nDaniel',
    replyDraft:
      'Hi Daniel,\n\nConfirmed — I will be there Thursday at 10am with the sign-off ready.\n\nThanks,\nYou',
    extractTask: null,
  },
  {
    id: 'em-6',
    threadId: 'th-northwind',
    subject: 'Vendor contract — redlines v3',
    senderName: 'Priya Sharma',
    sender: 'priya@northwind.co',
    daysAgo: 1,
    hour: 16,
    classification: 'action',
    classConfidence: 0.94,
    classReasoning: 'Asks you to review a specific contract section and respond.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-vendor',
    matterId: 'mat-northwind',
    bodyPreview: 'Updated redlines attached — please review §4.2 on liability and send back today.',
    bodyFull:
      'Hi,\n\nv3 of the redlines is attached. The main open item is §4.2 on liability caps — legal needs your read before we can countersign. Could you review and send back today?\n\nBest,\nPriya',
    replyDraft:
      'Hi Priya,\n\nReviewed §4.2 — the liability cap works for us. One small note: please align the cap figure with the value in §2.1. Otherwise we are good to countersign.\n\nBest,\nYou',
    extractTask: {
      title: 'Review the Northwind contract changes',
      summary: 'Legal is blocked on your read of the liability cap before the contract can be countersigned.',
      actionItems: ['Review the liability cap section', 'Send notes back to Priya'],
      urgency: 5,
      impact: 4,
      priorityReason: 'Blocks the contract countersignature and Priya asked for it today.',
      deadlineOffset: 0,
      matterId: 'mat-northwind',
      projectId: 'prj-vendor',
    },
  },
  {
    id: 'em-7',
    threadId: 'th-soc2',
    subject: 'SOC-2 renewal — documentation needs approval',
    senderName: 'Trust & Compliance',
    sender: 'compliance@securevault.com',
    daysAgo: 4,
    hour: 10,
    classification: 'action',
    classConfidence: 0.86,
    classReasoning: 'Renewal request requiring your approval before a deadline.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-vendor',
    matterId: null,
    bodyPreview: 'Your annual SOC-2 vendor renewal is ready for approval.',
    bodyFull:
      'Hello,\n\nYour annual SOC-2 vendor assessment renewal is ready. Please review the attached documentation and approve so coverage continues without a lapse.\n\n— Trust & Compliance',
    replyDraft:
      'Hi,\n\nReviewed and approved — the renewal documentation looks complete. Please proceed.\n\nThanks,\nYou',
    extractTask: null,
  },
  {
    id: 'em-8',
    threadId: 'th-invoice-linear',
    subject: 'Your receipt from Linear',
    senderName: 'Linear',
    sender: 'billing@linear.app',
    daysAgo: 2,
    hour: 6,
    classification: 'ignore',
    classConfidence: 0.97,
    classReasoning: 'Automated billing receipt — no action required.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: null,
    matterId: null,
    bodyPreview: 'Thanks for your payment. Your receipt is attached.',
    bodyFull: 'Thanks for your payment of $96.00. This email is your receipt — no action needed.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-9',
    threadId: 'th-po',
    subject: 'PO #4471 approved',
    senderName: 'Acme Procurement',
    sender: 'ap@acme.io',
    daysAgo: 5,
    hour: 14,
    classification: 'awareness',
    classConfidence: 0.84,
    classReasoning: 'Confirmation that a purchase order was approved — informational.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-vendor',
    matterId: null,
    bodyPreview: 'PO #4471 has been approved and sent to the vendor.',
    bodyFull: 'PO #4471 was approved this afternoon and has been sent to the vendor. Sharing for your records.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-10',
    threadId: 'th-backend',
    subject: 'Senior Backend candidate — interview feedback needed',
    senderName: 'Talent Team',
    sender: 'talent@acme.io',
    daysAgo: 1,
    hour: 12,
    classification: 'action',
    classConfidence: 0.92,
    classReasoning: 'Requests your written interview feedback to move a candidate forward.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-hiring',
    matterId: 'mat-backend',
    bodyPreview: 'Please submit your scorecard for the senior backend candidate so we can move forward.',
    bodyFull:
      'Hi,\n\nThe panel is waiting on your scorecard for the senior backend candidate (interviewed Tuesday). Could you submit your written feedback so we can make a decision this week?\n\nThanks,\nTalent',
    replyDraft:
      'Hi,\n\nScorecard submitted. Short version: strong on system design, solid coding, would hire. Recommend moving to the offer stage.\n\nThanks,\nYou',
    extractTask: null,
  },
  {
    id: 'em-11',
    threadId: 'th-offer',
    subject: 'Re: Offer discussion — a couple of questions',
    senderName: 'Jordan Avery',
    sender: 'jordan.avery@gmail.com',
    daysAgo: 0,
    hour: 7,
    classification: 'action',
    classConfidence: 0.89,
    classReasoning: 'Candidate awaiting your reply on offer questions — time-sensitive.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-hiring',
    matterId: 'mat-backend',
    bodyPreview: 'Thanks for the offer! Two questions on the equity and start date before I sign.',
    bodyFull:
      'Hi,\n\nThank you for the offer — I am excited. Two quick questions before I sign: (1) is there flexibility on the start date, two weeks later? (2) could you explain the equity vesting schedule?\n\nLooking forward to hearing back.\n\nJordan',
    replyDraft:
      'Hi Jordan,\n\nGreat to hear you are excited. (1) A two-week-later start date is no problem. (2) Equity vests over four years with a one-year cliff, then monthly. Happy to walk through it on a call if useful.\n\nLet me know if anything else would help.\n\nBest,\nYou',
    extractTask: {
      title: 'Answer Jordan’s offer questions',
      summary: 'A candidate is waiting on answers about start date and equity before signing the offer.',
      actionItems: ['Confirm start-date flexibility', 'Explain the equity vesting schedule', 'Reply to Jordan'],
      urgency: 4,
      impact: 5,
      priorityReason: 'A strong candidate may cool off if the reply is slow.',
      deadlineOffset: 1,
      matterId: 'mat-backend',
      projectId: 'prj-hiring',
    },
  },
  {
    id: 'em-12',
    threadId: 'th-fe-interview',
    subject: 'Interview scheduled: Frontend candidate',
    senderName: 'Acme Calendar',
    sender: 'calendar@acme.io',
    daysAgo: 2,
    hour: 17,
    classification: 'awareness',
    classConfidence: 0.8,
    classReasoning: 'Calendar notification — informational.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-hiring',
    matterId: null,
    bodyPreview: 'A frontend candidate interview has been added to your calendar.',
    bodyFull: 'An interview with a frontend candidate has been added to your calendar for next week. No action needed now.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-13',
    threadId: 'th-homepage',
    subject: 'Homepage redesign — round 2 feedback',
    senderName: 'Lena Cole',
    sender: 'lena@atlasstudio.co',
    daysAgo: 1,
    hour: 10,
    classification: 'action',
    classConfidence: 0.93,
    classReasoning: 'Client requesting revisions to a deliverable.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-atlas',
    matterId: 'mat-homepage',
    bodyPreview: 'Round 2 feedback attached — mostly the hero and testimonials section.',
    bodyFull:
      'Hi,\n\nThanks for round 1 — really close. Round 2 feedback is attached: the hero needs a tighter headline and the testimonials section should move above the pricing. Could you turn these around this week?\n\nLena',
    replyDraft:
      'Hi Lena,\n\nThanks for the notes — all clear. I will tighten the hero headline and reorder testimonials above pricing, and have round 3 to you by Thursday.\n\nBest,\nYou',
    extractTask: null,
  },
  {
    id: 'em-14',
    threadId: 'th-atlas-invoice',
    subject: 'Re: Invoice + next milestone',
    senderName: 'Lena Cole',
    sender: 'lena@atlasstudio.co',
    daysAgo: 3,
    hour: 11,
    classification: 'action',
    classConfidence: 0.87,
    classReasoning: 'Client asking you to send an invoice for completed work.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-atlas',
    matterId: null,
    bodyPreview: 'Milestone 1 is signed off — please send the invoice when you can.',
    bodyFull:
      'Hi,\n\nMilestone 1 is signed off on our side — thank you. Whenever you get a chance, please send the invoice so finance can process it this cycle.\n\nLena',
    replyDraft:
      'Hi Lena,\n\nGreat news on milestone 1. Invoice for milestone 1 is attached — payable within 14 days. Let me know if finance needs anything else.\n\nThanks,\nYou',
    extractTask: null,
  },
  {
    id: 'em-15',
    threadId: 'th-brand-assets',
    subject: 'Brand assets uploaded to Drive',
    senderName: 'Atlas Studio',
    sender: 'team@atlasstudio.co',
    daysAgo: 4,
    hour: 9,
    classification: 'awareness',
    classConfidence: 0.82,
    classReasoning: 'Notification that files were shared — informational.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-atlas',
    matterId: null,
    bodyPreview: 'The latest brand assets are now in the shared Drive folder.',
    bodyFull: 'The latest logo and brand assets have been uploaded to the shared Drive folder. Sharing for visibility.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-16',
    threadId: 'th-lease',
    subject: 'Lease renewal — please confirm by month end',
    senderName: 'Maple Living',
    sender: 'property@maple-living.com',
    daysAgo: 2,
    hour: 18,
    classification: 'action',
    classConfidence: 0.9,
    classReasoning: 'Requires your decision and confirmation before a deadline.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-personal',
    matterId: 'mat-lease',
    bodyPreview: 'Your lease is up for renewal — please confirm your intention by the end of the month.',
    bodyFull:
      'Dear resident,\n\nYour current lease expires soon. To renew for another 12 months at the rate in the attached letter, please confirm in writing by the end of this month. If we do not hear back we will assume you are not renewing.\n\nMaple Living Property Management',
    replyDraft:
      'Hello,\n\nI would like to renew my lease for another 12 months at the rate in your letter. Please send the renewal paperwork and let me know if anything else is needed.\n\nThank you,\nYou',
    extractTask: {
      title: 'Confirm apartment lease renewal',
      summary: 'Confirm in writing that you want to renew the apartment lease for another 12 months.',
      actionItems: ['Decide on renewal', 'Send written confirmation to the property manager'],
      urgency: 3,
      impact: 5,
      priorityReason: 'The lease is assumed cancelled if you do not reply by month end.',
      deadlineOffset: 6,
      matterId: 'mat-lease',
      projectId: 'prj-personal',
    },
  },
  {
    id: 'em-17',
    threadId: 'th-dentist',
    subject: 'Appointment reminder',
    senderName: 'Bright Smile Dental',
    sender: 'appointments@brightsmile.com',
    daysAgo: 1,
    hour: 8,
    classification: 'awareness',
    classConfidence: 0.85,
    classReasoning: 'Appointment reminder — informational.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: 'prj-personal',
    matterId: null,
    bodyPreview: 'This is a reminder of your upcoming dental check-up.',
    bodyFull: 'This is a friendly reminder of your upcoming dental check-up. Reply CANCEL if you need to reschedule.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-18',
    threadId: 'th-flight',
    subject: 'Your flight itinerary — confirmation',
    senderName: 'SkyHop Airlines',
    sender: 'noreply@skyhop.com',
    daysAgo: 6,
    hour: 20,
    classification: 'awareness',
    classConfidence: 0.83,
    classReasoning: 'Travel confirmation — informational.',
    awaitingReview: false,
    hasAttachments: true,
    projectId: 'prj-personal',
    matterId: null,
    bodyPreview: 'Your flight is booked. Itinerary and check-in details attached.',
    bodyFull: 'Your flight is active. The full itinerary and check-in details are attached. Online check-in opens 24 hours before departure.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-19',
    threadId: 'th-promo',
    subject: '🔥 50% off all plans — this week only!',
    senderName: 'CloudTools',
    sender: 'deals@cloudtools.io',
    daysAgo: 1,
    hour: 5,
    classification: 'ignore',
    classConfidence: 0.98,
    classReasoning: 'Marketing promotion — no action required.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: null,
    matterId: null,
    bodyPreview: 'Upgrade now and save 50% on every plan. Offer ends Sunday.',
    bodyFull: 'Limited-time offer! Upgrade now and save 50% on every plan. Offer ends Sunday — do not miss out.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-20',
    threadId: 'th-jobs',
    subject: '12 new jobs match your profile',
    senderName: 'JobBoard',
    sender: 'digest@jobboard.com',
    daysAgo: 0,
    hour: 6,
    classification: 'ignore',
    classConfidence: 0.96,
    classReasoning: 'Automated recommendation digest — no action required.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: null,
    matterId: null,
    bodyPreview: '12 new roles match your saved search this week.',
    bodyFull: 'Based on your saved search, 12 new roles were posted this week. View them on JobBoard.',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-21',
    threadId: 'th-newsletter',
    subject: 'Product Weekly — Issue #88',
    senderName: 'Product Weekly',
    sender: 'hello@productweekly.com',
    daysAgo: 2,
    hour: 7,
    classification: 'ignore',
    classConfidence: 0.95,
    classReasoning: 'Newsletter — no action required.',
    awaitingReview: false,
    hasAttachments: false,
    projectId: null,
    matterId: null,
    bodyPreview: 'This week: shipping cadence, pricing experiments, and a great onboarding teardown.',
    bodyFull: 'In this issue: shipping cadence, pricing experiments, and an onboarding teardown worth a read. Enjoy!',
    replyDraft: null,
    extractTask: null,
  },
  {
    id: 'em-22',
    threadId: 'th-quick-q',
    subject: 'Quick question about last week',
    senderName: 'Sam Whitfield',
    sender: 'sam.w@gmail.com',
    daysAgo: 1,
    hour: 19,
    classification: 'uncertain',
    classConfidence: 0.48,
    classReasoning: 'Vague message — not enough context to tell if a task is required.',
    awaitingReview: true,
    hasAttachments: false,
    projectId: null,
    matterId: null,
    bodyPreview: 'Hey — quick question about what we discussed last week. Got a minute?',
    bodyFull:
      'Hey,\n\nQuick question about what we talked through last week — did the numbers end up working out? Got a minute to sync?\n\nSam',
    replyDraft:
      'Hi Sam,\n\nThanks for checking in — yes, the numbers worked out. Happy to sync; I am free tomorrow afternoon, send a time that suits you.\n\nBest,\nYou',
    extractTask: {
      title: 'Reply to Sam about last week’s numbers',
      summary: 'Sam is waiting on confirmation about last week’s numbers and wants to sync.',
      actionItems: ['Confirm the numbers worked out', 'Propose a time to sync'],
      urgency: 2,
      impact: 2,
      priorityReason: 'A light personal follow-up with no hard deadline.',
      deadlineOffset: 3,
      matterId: null,
      projectId: null,
    },
  },
]

// ---------- Tasks ----------

export interface TaskTemplate {
  id: string
  title: string
  summary: string
  actionItems: string[]
  status: DemoTaskStatus
  urgency: number
  impact: number
  priorityReason: string
  /** Effective deadline in days from "today" (negative = overdue). */
  deadlineOffset: number
  /** Span in days for the gantt bar (start = deadline − durationDays). */
  durationDays: number
  /** completedAt in days from today, when status === 'completed'. */
  completedOffset: number | null
  source: 'email' | 'manual'
  sourceEmailId: string | null
  projectId: string | null
  matterId: string | null
}

export const DEMO_TASKS: TaskTemplate[] = [
  {
    id: 'tk-2',
    title: 'Review and edit launch page copy',
    summary: 'Edit the hero and pricing sections of the launch page copy before it goes to design.',
    actionItems: ['Edit the hero section', 'Edit the pricing section', 'Hand the doc back to Sofia'],
    status: 'active',
    urgency: 4,
    impact: 4,
    priorityReason: 'Design is blocked on this and the deadline is tomorrow.',
    deadlineOffset: 1,
    durationDays: 1,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-2',
    projectId: 'prj-q2launch',
    matterId: null,
  },
  {
    id: 'tk-3',
    title: 'Confirm attendance for Q2 go / no-go meeting',
    summary: 'Daniel needs confirmation you can attend the go/no-go meeting where your sign-off is on the agenda.',
    actionItems: ['Confirm attendance with Daniel', 'Prepare the sign-off summary'],
    status: 'active',
    urgency: 4,
    impact: 3,
    priorityReason: 'The meeting cannot proceed without your sign-off.',
    deadlineOffset: 2,
    durationDays: 2,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-5',
    projectId: 'prj-q2launch',
    matterId: 'mat-signoff',
  },
  {
    id: 'tk-5',
    title: 'Approve SOC-2 renewal documentation',
    summary: 'Review and approve the annual SOC-2 vendor renewal so coverage does not lapse.',
    actionItems: ['Review the renewal documentation', 'Approve the renewal'],
    status: 'active',
    urgency: 3,
    impact: 4,
    priorityReason: 'Compliance coverage lapses if this is not approved in time.',
    deadlineOffset: 4,
    durationDays: 2,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-7',
    projectId: 'prj-vendor',
    matterId: null,
  },
  {
    id: 'tk-6',
    title: 'Send interview feedback for senior backend candidate',
    summary: 'The hiring panel is waiting on your scorecard before it can make a decision.',
    actionItems: ['Write the scorecard', 'Submit feedback to the talent team'],
    status: 'active',
    urgency: 4,
    impact: 3,
    priorityReason: 'The panel is blocked on your feedback and it is already overdue.',
    deadlineOffset: -1,
    durationDays: 2,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-10',
    projectId: 'prj-hiring',
    matterId: 'mat-backend',
  },
  {
    id: 'tk-8',
    title: 'Apply round 2 homepage feedback for Atlas',
    summary: 'Tighten the hero headline and move testimonials above pricing per the client’s round 2 notes.',
    actionItems: ['Tighten the hero headline', 'Move testimonials above pricing', 'Send round 3 to Lena'],
    status: 'active',
    urgency: 3,
    impact: 4,
    priorityReason: 'Client deliverable due this week.',
    deadlineOffset: 3,
    durationDays: 3,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-13',
    projectId: 'prj-atlas',
    matterId: 'mat-homepage',
  },
  {
    id: 'tk-9',
    title: 'Send Atlas milestone 1 invoice',
    summary: 'Atlas signed off milestone 1 — looks like the right moment to issue the invoice so finance can process it this cycle.',
    actionItems: ['Prepare the milestone 1 invoice', 'Send it to Lena'],
    status: 'ai_suggestion',
    urgency: 3,
    impact: 3,
    priorityReason: 'Slips this billing cycle if not sent in the next couple of days.',
    deadlineOffset: 2,
    durationDays: 1,
    completedOffset: null,
    source: 'email',
    sourceEmailId: 'em-14',
    projectId: 'prj-atlas',
    matterId: null,
  },
  {
    id: 'tk-11',
    title: 'Draft the Q2 launch retro deck',
    summary: 'Prepare the retrospective deck for the Q2 launch team review.',
    actionItems: ['Collect launch metrics', 'Draft the retro slides'],
    status: 'active',
    urgency: 2,
    impact: 3,
    priorityReason: 'Useful but not blocking — there is room before the review.',
    deadlineOffset: 9,
    durationDays: 4,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: null,
  },
  {
    id: 'tk-12',
    title: 'Follow up with Northwind on the signed contract',
    summary: 'Northwind contract review is wrapping — want me to chase Priya for the countersigned copy once §4.2 is resolved?',
    actionItems: ['Check whether §4.2 is resolved', 'Ask Priya for the countersigned copy'],
    status: 'ai_suggestion',
    urgency: 2,
    impact: 4,
    priorityReason: 'Keeps the renewal moving but depends on the §4.2 review first.',
    deadlineOffset: 7,
    durationDays: 2,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-vendor',
    matterId: 'mat-northwind',
  },
  {
    id: 'tk-13',
    title: 'Book travel for the Atlas client kickoff',
    summary: 'Atlas kickoff is on the calendar — should I get flights and accommodation booked while there is still lead time?',
    actionItems: ['Book flights', 'Book accommodation'],
    status: 'ai_suggestion',
    urgency: 2,
    impact: 2,
    priorityReason: 'Plenty of lead time — low urgency for now.',
    deadlineOffset: 12,
    durationDays: 3,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-atlas',
    matterId: null,
  },
  {
    id: 'tk-14',
    title: 'Improve onboarding flow from beta feedback',
    summary: 'Address the recurring beta feedback that onboarding steps are easy to skip and hard to return to.',
    actionItems: ['Audit the onboarding flow', 'Add back-navigation between steps'],
    status: 'ai_suggestion',
    urgency: 3,
    impact: 4,
    priorityReason: 'Affects the first impression of every new user.',
    deadlineOffset: 4,
    durationDays: 3,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: 'mat-beta',
  },
  {
    id: 'tk-15',
    title: 'Sign off the staging deploy checklist',
    summary: 'Final checklist review for the v2 staging deploy.',
    actionItems: ['Review the deploy checklist', 'Sign off'],
    status: 'completed',
    urgency: 3,
    impact: 3,
    priorityReason: 'Completed ahead of the launch sign-off.',
    deadlineOffset: -1,
    durationDays: 1,
    completedOffset: -1,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: null,
  },
  {
    id: 'tk-17',
    title: 'Complete the vendor security questionnaire',
    summary: 'A vendor needs the security questionnaire returned before they can proceed — looks like a 30-minute pass.',
    actionItems: ['Fill in the security questionnaire', 'Return it to the vendor'],
    status: 'ai_suggestion',
    urgency: 3,
    impact: 3,
    priorityReason: 'Unblocks the vendor and clears the queue.',
    deadlineOffset: 5,
    durationDays: 2,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-vendor',
    matterId: null,
  },
  {
    id: 'tk-18',
    title: 'Ship the Q2 launch announcement',
    summary: 'Final announcement copy published to the company blog and shared with the team.',
    actionItems: ['Publish the announcement', 'Share the link with the team'],
    status: 'completed',
    urgency: 4,
    impact: 4,
    priorityReason: 'Completed ahead of the launch.',
    deadlineOffset: -2,
    durationDays: 2,
    completedOffset: -2,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: null,
  },
  // tk-50 / tk-51: extra Active tasks so the workload feels real-sized.
  // tk-52: another AI suggestion the inbox surfaced overnight.
  {
    id: 'tk-50',
    title: 'Draft Q3 launch readiness checklist',
    summary: 'Pull together the Q3 launch readiness checklist so we can lock the go-live gates by the end of the sprint.',
    actionItems: ['List launch gates', 'Assign owners per gate', 'Circulate for review'],
    status: 'active',
    urgency: 3,
    impact: 4,
    priorityReason: 'Locks the Q3 launch on a clear cadence.',
    deadlineOffset: 6,
    durationDays: 4,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: null,
  },
  {
    id: 'tk-51',
    title: 'Review pricing experiment results',
    summary: 'Open the latest pricing experiment readout and decide which tier moves to GA.',
    actionItems: ['Read the experiment writeup', 'Note recommendation', 'Share decision with marketing'],
    status: 'active',
    urgency: 3,
    impact: 3,
    priorityReason: 'Marketing is waiting on this call before they finalise launch copy.',
    deadlineOffset: 5,
    durationDays: 2,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-q2launch',
    matterId: null,
  },
  {
    id: 'tk-52',
    title: 'Reply to the Atlas brand budget thread',
    summary: 'Atlas asked about the brand budget split — looks like a quick reply with the agreed ratios will unblock them.',
    actionItems: ['Confirm the budget ratios with finance', 'Send a short reply to Lena'],
    status: 'ai_suggestion',
    urgency: 3,
    impact: 3,
    priorityReason: 'Two-line reply unblocks a client decision.',
    deadlineOffset: 3,
    durationDays: 1,
    completedOffset: null,
    source: 'manual',
    sourceEmailId: null,
    projectId: 'prj-atlas',
    matterId: null,
  },
]
